// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * An achievement/crown earned by a user
 */
export type Achievement = {
    achievement_type: AchievementType;
    created_at: string;
    earned_at: string;
    effort_count?: number | null;
    effort_id?: string | null;
    id: string;
    lost_at?: string | null;
    segment_id: string;
    user_id: string;
};

/**
 * Holder of an achievement with their details
 */
export type AchievementHolder = {
    achievement_type: AchievementType;
    earned_at: string;
    effort_count?: number | null;
    elapsed_time_seconds?: number | null;
    user_id: string;
    user_name: string;
};

/**
 * Type of achievement/crown
 */
export type AchievementType = 'kom' | 'qom' | 'course_record';

/**
 * Achievement with segment details for display
 */
export type AchievementWithSegment = {
    achievement_type: AchievementType;
    earned_at: string;
    effort_count?: number | null;
    effort_id?: string | null;
    id: string;
    lost_at?: string | null;
    segment_activity_type_id: string;
    segment_distance_meters: number;
    segment_id: string;
    segment_name: string;
    user_id: string;
};

export type Activity = {
    activity_type_id: string;
    id: string;
    name: string;
    object_store_path: string;
    segment_types?: Array<string> | null;
    submitted_at: string;
    type_boundaries?: Array<string> | null;
    user_id: string;
    visibility: string;
};

/**
 * Segment effort with segment details, for displaying on activity detail page.
 */
export type ActivitySegmentEffort = {
    activity_type_id: string;
    effort_id: string;
    elapsed_time_seconds: number;
    end_fraction?: number | null;
    is_personal_record: boolean;
    rank: number;
    segment_distance: number;
    segment_id: string;
    segment_name: string;
    start_fraction?: number | null;
    started_at: string;
};

/**
 * Row from the activity_types table
 */
export type ActivityTypeRow = {
    created_at: string;
    created_by?: string | null;
    id: string;
    is_builtin: boolean;
    name: string;
};

/**
 * Request to add a comment.
 */
export type AddCommentRequest = {
    content: string;
    parent_id?: string | null;
};

/**
 * Age group for demographic filtering (5-year brackets for younger, 10-year for older)
 */
export type AgeGroup = 'all' | '18-24' | '25-29' | '30-34' | '35-39' | '40-49' | '50-59' | '60+';

export type AuthResponse = {
    token: string;
    user: UserResponse;
};

/**
 * Request to change a member's role
 */
export type ChangeMemberRoleRequest = {
    role: TeamRole;
};

export type ClimbCategoryFilter = 'hc' | 'cat1' | 'cat2' | 'cat3' | 'cat4' | 'flat';

/**
 * A comment on an activity
 */
export type Comment = {
    activity_id: string;
    content: string;
    created_at: string;
    deleted_at?: string | null;
    id: string;
    parent_id?: string | null;
    updated_at?: string | null;
    user_id: string;
};

/**
 * Comment with user info for display
 */
export type CommentWithUser = {
    activity_id: string;
    content: string;
    created_at: string;
    id: string;
    parent_id?: string | null;
    updated_at?: string | null;
    user_id: string;
    user_name: string;
};

/**
 * Country with user count for the countries dropdown
 */
export type CountryStats = {
    country: string;
    user_count: number;
};

/**
 * Request to create a custom activity type
 */
export type CreateActivityTypeRequest = {
    name: string;
};

export type CreateSegmentRequest = {
    /**
     * Optional if source_activity_id is provided (inherits from the activity).
     * Required if source_activity_id is not provided.
     */
    activity_type_id?: string | null;
    description?: string | null;
    name: string;
    points: Array<SegmentPoint>;
    /**
     * Optional: the activity this segment was created from.
     * If provided, the segment inherits its activity_type_id and guarantees that activity gets the first effort.
     */
    source_activity_id?: string | null;
    /**
     * Team IDs to share the segment with (for teams_only visibility)
     */
    team_ids?: Array<string> | null;
    visibility?: string;
};

/**
 * Request to create a team
 */
export type CreateTeamRequest = {
    avatar_url?: string | null;
    description?: string | null;
    join_policy?: TeamJoinPolicy;
    name: string;
    visibility?: TeamVisibility;
};

/**
 * Entry in global crown count leaderboard
 */
export type CrownCountEntry = {
    kom_count: number;
    qom_count: number;
    rank: number;
    total_crowns: number;
    user_id: string;
    user_name: string;
};

export type DiscoverTeamsQuery = {
    limit?: number;
    offset?: number;
};

/**
 * Entry in global distance leaderboard
 */
export type DistanceLeaderEntry = {
    activity_count: number;
    rank: number;
    total_distance_meters: number;
    user_id: string;
    user_name: string;
};

/**
 * Activity with user and stats for the feed
 */
export type FeedActivity = {
    activity_type_id: string;
    comment_count: number;
    distance?: number | null;
    duration?: number | null;
    elevation_gain?: number | null;
    id: string;
    kudos_count: number;
    name: string;
    submitted_at: string;
    user_id: string;
    user_name: string;
    visibility: string;
};

/**
 * Query parameters for activity feed.
 */
export type FeedQuery = {
    limit?: number;
    offset?: number;
};

/**
 * A follow relationship between two users
 */
export type Follow = {
    created_at: string;
    follower_id: string;
    following_id: string;
};

/**
 * Query parameters for follow list endpoints.
 */
export type FollowListQuery = {
    limit?: number;
    offset?: number;
};

/**
 * Response for follower/following lists.
 */
export type FollowListResponse = {
    total_count: number;
    users: Array<UserSummary>;
};

/**
 * Response for follow status check.
 */
export type FollowStatusResponse = {
    is_following: boolean;
};

/**
 * User gender for demographic filtering
 */
export type Gender = 'male' | 'female' | 'other' | 'prefer_not_to_say';

/**
 * Gender filter for leaderboards (includes "all" option)
 */
export type GenderFilter = 'all' | 'male' | 'female';

/**
 * Query parameters for achievements endpoints.
 */
export type GetAchievementsQuery = {
    include_lost?: boolean;
};

/**
 * Query parameters for global leaderboards.
 */
export type GlobalLeaderboardQuery = {
    limit?: number;
    offset?: number;
};

/**
 * Request to invite a user to a team
 */
export type InviteToTeamRequest = {
    email: string;
    role?: TeamRole;
};

/**
 * Request to join a team
 */
export type JoinTeamRequest = {
    message?: string | null;
};

/**
 * User who gave kudos
 */
export type KudosGiver = {
    created_at: string;
    user_id: string;
    user_name: string;
};

/**
 * Response for kudos operations.
 */
export type KudosResponse = {
    given: boolean;
    kudos_count: number;
};

/**
 * Response for kudos status check.
 */
export type KudosStatusResponse = {
    has_given: boolean;
};

/**
 * A single entry in the leaderboard with user info and ranking
 */
export type LeaderboardEntry = {
    average_speed_mps?: number | null;
    effort_id: string;
    elapsed_time_seconds: number;
    gap_seconds?: number | null;
    is_personal_record: boolean;
    moving_time_seconds?: number | null;
    rank: number;
    started_at: string;
    user_id: string;
    user_name: string;
};

/**
 * Query parameters for filtered leaderboard requests
 */
export type LeaderboardFilters = {
    age_group?: AgeGroup;
    country?: string | null;
    gender?: GenderFilter;
    limit?: number;
    offset?: number;
    scope?: LeaderboardScope;
    weight_class?: WeightClass;
};

/**
 * Echoed filters in leaderboard response
 */
export type LeaderboardFiltersResponse = {
    age_group: AgeGroup;
    country?: string | null;
    gender: GenderFilter;
    limit: number;
    offset: number;
    scope: LeaderboardScope;
    weight_class: WeightClass;
};

/**
 * User's position in the leaderboard with surrounding entries
 */
export type LeaderboardPosition = {
    entries_above: Array<LeaderboardEntry>;
    entries_below: Array<LeaderboardEntry>;
    total_count: number;
    user_entry: LeaderboardEntry;
    user_rank: number;
};

/**
 * Response for paginated leaderboard
 */
export type LeaderboardResponse = {
    entries: Array<LeaderboardEntry>;
    filters: LeaderboardFiltersResponse;
    total_count: number;
};

/**
 * Time scope for leaderboard filtering
 */
export type LeaderboardScope = 'all_time' | 'year' | 'month' | 'week';

export type ListSegmentsQuery = {
    activity_type_id?: string | null;
    climb_category?: null | ClimbCategoryFilter;
    limit?: number;
    /**
     * Maximum distance in meters
     */
    max_distance_meters?: number | null;
    /**
     * Minimum distance in meters
     */
    min_distance_meters?: number | null;
    /**
     * Case-insensitive name search
     */
    search?: string | null;
    /**
     * Sort field
     */
    sort_by?: SegmentSortBy;
    /**
     * Sort order
     */
    sort_order?: SortOrder;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type NearbySegmentsQuery = {
    lat: number;
    limit?: number | null;
    lon: number;
    radius_meters?: number | null;
};

/**
 * A notification for a user
 */
export type Notification = {
    actor_id?: string | null;
    created_at: string;
    id: string;
    message?: string | null;
    notification_type: string;
    read_at?: string | null;
    target_id?: string | null;
    target_type?: string | null;
    user_id: string;
};

/**
 * Type of notification
 */
export type NotificationType = 'follow' | 'kudos' | 'comment' | 'crown_achieved' | 'crown_lost' | 'personal_record';

/**
 * Notification with actor details for display
 */
export type NotificationWithActor = {
    actor_id?: string | null;
    actor_name?: string | null;
    created_at: string;
    id: string;
    message?: string | null;
    notification_type: string;
    read_at?: string | null;
    target_id?: string | null;
    target_type?: string | null;
    user_id: string;
};

/**
 * Query parameters for notifications.
 */
export type NotificationsQuery = {
    limit?: number;
    offset?: number;
};

/**
 * Response for notifications list with unread count
 */
export type NotificationsResponse = {
    notifications: Array<NotificationWithActor>;
    total_count: number;
    unread_count: number;
};

export type PreviewSegmentRequest = {
    points: Array<SegmentPoint>;
};

export type PreviewSegmentResponse = {
    average_grade?: number | null;
    climb_category?: number | null;
    distance_meters: number;
    elevation_gain_meters?: number | null;
    elevation_loss_meters?: number | null;
    max_grade?: number | null;
    point_count: number;
    validation: SegmentValidation;
};

export type RegisterRequest = {
    email: string;
    name: string;
    password: string;
};

export type ReprocessResult = {
    activities_checked: number;
    efforts_created: number;
    segment_id: string;
};

/**
 * Activity type resolution query.
 */
export type ResolveTypeQuery = {
    name: string;
};

/**
 * Activity type resolution response.
 */
export type ResolveTypeResponse = {
    /**
     * "exact", "ambiguous", or "not_found"
     */
    result: string;
    type_id?: string | null;
    type_ids?: Array<string> | null;
};

export type ReviewJoinRequestRequest = {
    approved: boolean;
};

export type Segment = {
    activity_type_id: string;
    average_grade?: number | null;
    climb_category?: number | null;
    created_at: string;
    creator_id: string;
    creator_name?: string | null;
    description?: string | null;
    distance_meters: number;
    elevation_gain_meters?: number | null;
    elevation_loss_meters?: number | null;
    id: string;
    max_grade?: number | null;
    name: string;
    visibility: string;
};

/**
 * Current achievement holders for a segment
 */
export type SegmentAchievements = {
    kom?: null | AchievementHolder;
    qom?: null | AchievementHolder;
    segment_id: string;
};

export type SegmentEffort = {
    activity_id: string;
    average_speed_mps?: number | null;
    created_at: string;
    elapsed_time_seconds: number;
    end_fraction?: number | null;
    id: string;
    is_personal_record: boolean;
    max_speed_mps?: number | null;
    moving_time_seconds?: number | null;
    segment_id: string;
    start_fraction?: number | null;
    started_at: string;
    user_id: string;
    user_name?: string | null;
};

export type SegmentPoint = {
    ele?: number | null;
    lat: number;
    lon: number;
};

export type SegmentSortBy = 'created_at' | 'name' | 'distance' | 'elevation_gain';

export type SegmentTrackData = {
    bounds: TrackBounds;
    points: Array<SegmentTrackPoint>;
};

export type SegmentTrackPoint = {
    ele?: number | null;
    lat: number;
    lon: number;
};

export type SegmentValidation = {
    errors: Array<string>;
    is_valid: boolean;
};

export type SegmentWithStats = Segment & {
    athlete_count: number;
    creator_name: string;
    effort_count: number;
};

/**
 * Request to share activity/segment with teams
 */
export type ShareWithTeamsRequest = {
    team_ids: Array<string>;
};

export type SortOrder = 'asc' | 'desc';

export type StarResponse = {
    starred: boolean;
};

/**
 * Starred segment with the user's effort stats, for the starred segments dashboard.
 */
export type StarredSegmentEffort = {
    activity_type_id: string;
    best_effort_date?: string | null;
    best_effort_rank?: number | null;
    best_time_seconds?: number | null;
    distance_meters: number;
    elevation_gain_meters?: number | null;
    leader_time_seconds?: number | null;
    segment_id: string;
    segment_name: string;
    user_effort_count: number;
};

/**
 * Platform statistics for the homepage
 */
export type Stats = {
    active_users: number;
    activities_uploaded: number;
    segments_created: number;
};

/**
 * A team for sharing activities and segments
 */
export type Team = {
    activity_count: number;
    avatar_url?: string | null;
    created_at: string;
    description?: string | null;
    id: string;
    join_policy: TeamJoinPolicy;
    member_count: number;
    name: string;
    owner_id: string;
    segment_count: number;
    updated_at?: string | null;
    visibility: TeamVisibility;
};

export type TeamContentQuery = {
    limit?: number;
    offset?: number;
};

/**
 * An invitation to join a team
 */
export type TeamInvitation = {
    accepted_at?: string | null;
    created_at: string;
    email: string;
    expires_at: string;
    id: string;
    invited_by: string;
    role: TeamRole;
    team_id: string;
    token: string;
};

/**
 * Invitation with additional context
 */
export type TeamInvitationWithDetails = {
    created_at: string;
    email: string;
    expires_at: string;
    id: string;
    invited_by: string;
    invited_by_name: string;
    role: TeamRole;
    team_id: string;
    team_name: string;
};

/**
 * Team join policy
 */
export type TeamJoinPolicy = 'open' | 'request' | 'invitation';

/**
 * Request to join a team
 */
export type TeamJoinRequest = {
    created_at: string;
    id: string;
    message?: string | null;
    reviewed_at?: string | null;
    reviewed_by?: string | null;
    status: string;
    team_id: string;
    user_id: string;
};

/**
 * Join request with user details for admin review
 */
export type TeamJoinRequestWithUser = {
    created_at: string;
    id: string;
    message?: string | null;
    status: string;
    team_id: string;
    user_id: string;
    user_name: string;
};

/**
 * Team member with user details
 */
export type TeamMember = {
    invited_by?: string | null;
    invited_by_name?: string | null;
    joined_at: string;
    role: TeamRole;
    user_id: string;
    user_name: string;
};

/**
 * A membership in a team
 */
export type TeamMembership = {
    invited_by?: string | null;
    joined_at: string;
    role: TeamRole;
    team_id: string;
    user_id: string;
};

/**
 * Team role enum
 */
export type TeamRole = 'owner' | 'admin' | 'member';

/**
 * Team summary for listings
 */
export type TeamSummary = {
    activity_count: number;
    avatar_url?: string | null;
    description?: string | null;
    id: string;
    member_count: number;
    name: string;
    segment_count: number;
};

/**
 * Team visibility (whether team is discoverable)
 */
export type TeamVisibility = 'public' | 'private';

/**
 * Team with additional context for the current user
 */
export type TeamWithMembership = Team & {
    is_member: boolean;
    owner_name: string;
    user_role?: null | TeamRole;
};

/**
 * Geographic bounds for a track.
 */
export type TrackBounds = {
    max_lat: number;
    max_lon: number;
    min_lat: number;
    min_lon: number;
};

/**
 * Activity track data response.
 */
export type TrackData = {
    bounds: TrackBounds;
    points: Array<TrackPoint>;
};

/**
 * Track point in activity track data.
 */
export type TrackPoint = {
    ele?: number | null;
    lat: number;
    lon: number;
    time?: string | null;
};

/**
 * Activity update request.
 */
export type UpdateActivityRequest = {
    activity_type_id?: string | null;
    name?: string | null;
    visibility?: string | null;
};

/**
 * Request to update user demographics
 */
export type UpdateDemographicsRequest = {
    birth_year?: number | null;
    country?: string | null;
    gender?: null | Gender;
    region?: string | null;
    weight_kg?: number | null;
};

/**
 * Request to update a team
 */
export type UpdateTeamRequest = {
    avatar_url?: string | null;
    description?: string | null;
    join_policy?: null | TeamJoinPolicy;
    name?: string | null;
    visibility?: null | TeamVisibility;
};

/**
 * Activity upload query parameters.
 */
export type UploadQuery = {
    activity_type_id: string;
    name: string;
    /**
     * Multi-sport: Comma-separated activity type UUIDs for each segment
     */
    segment_types?: string | null;
    /**
     * Comma-separated list of team IDs to share with (for teams_only visibility)
     */
    team_ids?: string | null;
    /**
     * Multi-sport: Comma-separated ISO-8601 timestamps marking segment boundaries
     */
    type_boundaries?: string | null;
    visibility?: string | null;
};

export type User = {
    created_at: string;
    email: string;
    id: string;
    name: string;
};

/**
 * User profile with follow counts for display
 */
export type UserProfile = {
    birth_year?: number | null;
    country?: string | null;
    created_at: string;
    email: string;
    follower_count: number;
    following_count: number;
    gender?: null | Gender;
    id: string;
    name: string;
    region?: string | null;
    weight_kg?: number | null;
};

export type UserResponse = {
    email: string;
    id: string;
    name: string;
};

/**
 * Summary of a user for follower/following lists
 */
export type UserSummary = {
    followed_at: string;
    follower_count: number;
    following_count: number;
    id: string;
    name: string;
};

/**
 * User profile with demographics
 */
export type UserWithDemographics = {
    birth_year?: number | null;
    country?: string | null;
    created_at: string;
    email: string;
    gender?: null | Gender;
    id: string;
    name: string;
    region?: string | null;
    weight_kg?: number | null;
};

export type Visibility = 'public' | 'private';

/**
 * Weight class for leaderboard filtering
 */
export type WeightClass = 'all' | 'featherweight' | 'lightweight' | 'welterweight' | 'middleweight' | 'cruiserweight' | 'heavyweight';

export type NewActivityData = {
    /**
     * GPX file upload
     */
    body?: unknown;
    path?: never;
    query: {
        /**
         * Activity type ID
         */
        activity_type_id: string;
        /**
         * Activity name
         */
        name: string;
        /**
         * Visibility: public, private, or teams_only
         */
        visibility?: string;
        /**
         * Comma-separated team IDs for teams_only visibility
         */
        team_ids?: string;
        /**
         * Comma-separated ISO-8601 timestamps for multi-sport segment boundaries
         */
        type_boundaries?: string;
        /**
         * Comma-separated activity type UUIDs for multi-sport segments
         */
        segment_types?: string;
    };
    url: '/activities/new';
};

export type NewActivityErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type NewActivityResponses = {
    /**
     * Activity created successfully
     */
    200: Activity;
};

export type NewActivityResponse = NewActivityResponses[keyof NewActivityResponses];

export type UnshareActivityFromTeamData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        activity_id: string;
        /**
         * Team ID
         */
        team_id: string;
    };
    query?: never;
    url: '/activities/{activity_id}/teams/{team_id}';
};

export type UnshareActivityFromTeamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - not the owner
     */
    403: unknown;
    /**
     * Activity or sharing not found
     */
    404: unknown;
};

export type UnshareActivityFromTeamResponses = {
    /**
     * Activity unshared from team
     */
    204: void;
};

export type UnshareActivityFromTeamResponse = UnshareActivityFromTeamResponses[keyof UnshareActivityFromTeamResponses];

export type DeleteActivityData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}';
};

export type DeleteActivityErrors = {
    /**
     * Activity not found
     */
    404: unknown;
};

export type DeleteActivityResponses = {
    /**
     * Activity deleted successfully
     */
    204: void;
};

export type DeleteActivityResponse = DeleteActivityResponses[keyof DeleteActivityResponses];

export type GetActivityData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}';
};

export type GetActivityErrors = {
    /**
     * Activity not found
     */
    404: unknown;
};

export type GetActivityResponses = {
    /**
     * Activity details
     */
    200: Activity;
};

export type GetActivityResponse = GetActivityResponses[keyof GetActivityResponses];

export type UpdateActivityData = {
    body: UpdateActivityRequest;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}';
};

export type UpdateActivityErrors = {
    /**
     * Activity not found
     */
    404: unknown;
};

export type UpdateActivityResponses = {
    /**
     * Activity updated successfully
     */
    200: Activity;
};

export type UpdateActivityResponse = UpdateActivityResponses[keyof UpdateActivityResponses];

export type GetCommentsData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/comments';
};

export type GetCommentsResponses = {
    /**
     * List of comments for the activity
     */
    200: Array<CommentWithUser>;
};

export type GetCommentsResponse = GetCommentsResponses[keyof GetCommentsResponses];

export type AddCommentData = {
    body: AddCommentRequest;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/comments';
};

export type AddCommentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Activity not found
     */
    404: unknown;
};

export type AddCommentResponses = {
    /**
     * Comment added successfully
     */
    200: CommentWithUser;
};

export type AddCommentResponse = AddCommentResponses[keyof AddCommentResponses];

export type DownloadGpxFileData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/download';
};

export type DownloadGpxFileErrors = {
    /**
     * Activity not found
     */
    404: unknown;
};

export type DownloadGpxFileResponses = {
    /**
     * GPX file download
     */
    200: unknown;
};

export type RemoveKudosData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/kudos';
};

export type RemoveKudosErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type RemoveKudosResponses = {
    /**
     * Kudos removed successfully
     */
    204: void;
};

export type RemoveKudosResponse = RemoveKudosResponses[keyof RemoveKudosResponses];

export type GetKudosGiversData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/kudos';
};

export type GetKudosGiversResponses = {
    /**
     * List of users who gave kudos
     */
    200: Array<KudosGiver>;
};

export type GetKudosGiversResponse = GetKudosGiversResponses[keyof GetKudosGiversResponses];

export type GiveKudosData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/kudos';
};

export type GiveKudosErrors = {
    /**
     * Cannot give kudos to own activity
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Activity not found
     */
    404: unknown;
};

export type GiveKudosResponses = {
    /**
     * Kudos given successfully
     */
    200: KudosResponse;
};

export type GiveKudosResponse = GiveKudosResponses[keyof GiveKudosResponses];

export type GetKudosStatusData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/kudos/status';
};

export type GetKudosStatusErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetKudosStatusResponses = {
    /**
     * Kudos status retrieved
     */
    200: KudosStatusResponse;
};

export type GetKudosStatusResponse = GetKudosStatusResponses[keyof GetKudosStatusResponses];

export type GetActivitySegmentsData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/segments';
};

export type GetActivitySegmentsErrors = {
    /**
     * Activity not found
     */
    404: unknown;
};

export type GetActivitySegmentsResponses = {
    /**
     * Segment efforts matched in this activity
     */
    200: Array<ActivitySegmentEffort>;
};

export type GetActivitySegmentsResponse = GetActivitySegmentsResponses[keyof GetActivitySegmentsResponses];

export type GetActivityTeamsData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/teams';
};

export type GetActivityTeamsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Activity not found
     */
    404: unknown;
};

export type GetActivityTeamsResponses = {
    /**
     * Teams the activity is shared with
     */
    200: Array<TeamSummary>;
};

export type GetActivityTeamsResponse = GetActivityTeamsResponses[keyof GetActivityTeamsResponses];

export type ShareActivityWithTeamsData = {
    body: ShareWithTeamsRequest;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/teams';
};

export type ShareActivityWithTeamsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - not the owner
     */
    403: unknown;
    /**
     * Activity not found
     */
    404: unknown;
};

export type ShareActivityWithTeamsResponses = {
    /**
     * Activity shared with teams
     */
    200: unknown;
};

export type GetActivityTrackData = {
    body?: never;
    path: {
        /**
         * Activity ID
         */
        id: string;
    };
    query?: never;
    url: '/activities/{id}/track';
};

export type GetActivityTrackErrors = {
    /**
     * Activity not found
     */
    404: unknown;
};

export type GetActivityTrackResponses = {
    /**
     * Track data with GPS points and bounds
     */
    200: TrackData;
};

export type GetActivityTrackResponse = GetActivityTrackResponses[keyof GetActivityTrackResponses];

export type ListActivityTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/activity-types';
};

export type ListActivityTypesResponses = {
    /**
     * List of all activity types
     */
    200: Array<ActivityTypeRow>;
};

export type ListActivityTypesResponse = ListActivityTypesResponses[keyof ListActivityTypesResponses];

export type CreateActivityTypeData = {
    body: CreateActivityTypeRequest;
    path?: never;
    query?: never;
    url: '/activity-types';
};

export type CreateActivityTypeErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type CreateActivityTypeResponses = {
    /**
     * Activity type created successfully
     */
    200: ActivityTypeRow;
};

export type CreateActivityTypeResponse = CreateActivityTypeResponses[keyof CreateActivityTypeResponses];

export type ResolveActivityTypeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Activity type name or alias to resolve
         */
        name: string;
    };
    url: '/activity-types/resolve';
};

export type ResolveActivityTypeResponses = {
    /**
     * Resolution result
     */
    200: ResolveTypeResponse;
};

export type ResolveActivityTypeResponse = ResolveActivityTypeResponses[keyof ResolveActivityTypeResponses];

export type GetActivityTypeData = {
    body?: never;
    path: {
        /**
         * Activity type ID
         */
        id: string;
    };
    query?: never;
    url: '/activity-types/{id}';
};

export type GetActivityTypeErrors = {
    /**
     * Activity type not found
     */
    404: unknown;
};

export type GetActivityTypeResponses = {
    /**
     * Activity type details
     */
    200: ActivityTypeRow;
};

export type GetActivityTypeResponse = GetActivityTypeResponses[keyof GetActivityTypeResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type LoginResponses = {
    /**
     * Login successful
     */
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type MeResponses = {
    /**
     * Current user info
     */
    200: UserResponse;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Email already registered
     */
    409: unknown;
};

export type RegisterResponses = {
    /**
     * Registration successful
     */
    200: AuthResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type DeleteCommentData = {
    body?: never;
    path: {
        /**
         * Comment ID
         */
        id: string;
    };
    query?: never;
    url: '/comments/{id}';
};

export type DeleteCommentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Comment not found or not owned by user
     */
    404: unknown;
};

export type DeleteCommentResponses = {
    /**
     * Comment deleted successfully
     */
    204: void;
};

export type DeleteCommentResponse = DeleteCommentResponses[keyof DeleteCommentResponses];

export type GetCountriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/countries';
};

export type GetCountriesResponses = {
    /**
     * List of countries with user counts
     */
    200: Array<CountryStats>;
};

export type GetCountriesResponse = GetCountriesResponses[keyof GetCountriesResponses];

export type GetFeedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of feed items to return
         */
        limit?: number;
        /**
         * Number of feed items to skip
         */
        offset?: number;
    };
    url: '/feed';
};

export type GetFeedErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetFeedResponses = {
    /**
     * Activity feed
     */
    200: Array<FeedActivity>;
};

export type GetFeedResponse = GetFeedResponses[keyof GetFeedResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Health check passed
     */
    200: unknown;
};

export type GetInvitationData = {
    body?: never;
    path: {
        /**
         * Invitation token
         */
        id: string;
    };
    query?: never;
    url: '/invitations/{id}';
};

export type GetInvitationErrors = {
    /**
     * Invitation has expired
     */
    400: unknown;
    /**
     * Invitation not found
     */
    404: unknown;
};

export type GetInvitationResponses = {
    /**
     * Invitation details
     */
    200: TeamInvitationWithDetails;
};

export type GetInvitationResponse = GetInvitationResponses[keyof GetInvitationResponses];

export type AcceptInvitationData = {
    body?: never;
    path: {
        /**
         * Invitation token
         */
        id: string;
    };
    query?: never;
    url: '/invitations/{id}/accept';
};

export type AcceptInvitationErrors = {
    /**
     * Invalid invitation or already a member
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Invitation not found
     */
    404: unknown;
};

export type AcceptInvitationResponses = {
    /**
     * Invitation accepted
     */
    200: unknown;
};

export type GetCrownLeaderboardData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Maximum number of entries to return
         */
        limit: number;
        /**
         * Number of entries to skip
         */
        offset: number;
    };
    url: '/leaderboard/crowns';
};

export type GetCrownLeaderboardResponses = {
    /**
     * Crown count leaderboard
     */
    200: Array<CrownCountEntry>;
};

export type GetCrownLeaderboardResponse = GetCrownLeaderboardResponses[keyof GetCrownLeaderboardResponses];

export type GetDistanceLeaderboardData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Maximum number of entries to return
         */
        limit: number;
        /**
         * Number of entries to skip
         */
        offset: number;
    };
    url: '/leaderboard/distance';
};

export type GetDistanceLeaderboardResponses = {
    /**
     * Distance leaderboard
     */
    200: Array<DistanceLeaderEntry>;
};

export type GetDistanceLeaderboardResponse = GetDistanceLeaderboardResponses[keyof GetDistanceLeaderboardResponses];

export type GetMyAchievementsData = {
    body?: never;
    path?: never;
    query?: {
        include_lost?: boolean;
    };
    url: '/me/achievements';
};

export type GetMyAchievementsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetMyAchievementsResponses = {
    /**
     * User achievements
     */
    200: Array<AchievementWithSegment>;
};

export type GetMyAchievementsResponse = GetMyAchievementsResponses[keyof GetMyAchievementsResponses];

export type GetNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of notifications to return
         */
        limit?: number;
        /**
         * Number of notifications to skip
         */
        offset?: number;
    };
    url: '/notifications';
};

export type GetNotificationsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetNotificationsResponses = {
    /**
     * List of notifications
     */
    200: NotificationsResponse;
};

export type GetNotificationsResponse = GetNotificationsResponses[keyof GetNotificationsResponses];

export type MarkAllNotificationsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read-all';
};

export type MarkAllNotificationsReadErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type MarkAllNotificationsReadResponses = {
    /**
     * All notifications marked as read
     */
    200: unknown;
};

export type MarkNotificationReadData = {
    body?: never;
    path: {
        /**
         * Notification ID
         */
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type MarkNotificationReadErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Notification not found
     */
    404: unknown;
};

export type MarkNotificationReadResponses = {
    /**
     * Notification marked as read
     */
    200: unknown;
};

export type ListSegmentsData = {
    body?: never;
    path?: never;
    query?: {
        activity_type_id?: string | null;
        limit?: number;
        /**
         * Case-insensitive name search
         */
        search?: string | null;
        /**
         * Sort field
         */
        sort_by?: SegmentSortBy;
        /**
         * Sort order
         */
        sort_order?: SortOrder;
        /**
         * Minimum distance in meters
         */
        min_distance_meters?: number | null;
        /**
         * Maximum distance in meters
         */
        max_distance_meters?: number | null;
        /**
         * Filter by climb category
         */
        climb_category?: null | ClimbCategoryFilter;
    };
    url: '/segments';
};

export type ListSegmentsErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListSegmentsResponses = {
    /**
     * List of segments
     */
    200: Array<Segment>;
};

export type ListSegmentsResponse = ListSegmentsResponses[keyof ListSegmentsResponses];

export type CreateSegmentData = {
    body: CreateSegmentRequest;
    path?: never;
    query?: never;
    url: '/segments';
};

export type CreateSegmentErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CreateSegmentResponses = {
    /**
     * Segment created successfully
     */
    200: Segment;
};

export type CreateSegmentResponse = CreateSegmentResponses[keyof CreateSegmentResponses];

export type GetNearbySegmentsData = {
    body?: never;
    path?: never;
    query: {
        lat: number;
        lon: number;
        radius_meters?: number | null;
        limit?: number | null;
    };
    url: '/segments/nearby';
};

export type GetNearbySegmentsErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetNearbySegmentsResponses = {
    /**
     * List of nearby segments
     */
    200: Array<Segment>;
};

export type GetNearbySegmentsResponse = GetNearbySegmentsResponses[keyof GetNearbySegmentsResponses];

export type PreviewSegmentData = {
    body: PreviewSegmentRequest;
    path?: never;
    query?: never;
    url: '/segments/preview';
};

export type PreviewSegmentErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PreviewSegmentResponses = {
    /**
     * Preview of segment metrics and validation
     */
    200: PreviewSegmentResponse;
};

export type PreviewSegmentResponse2 = PreviewSegmentResponses[keyof PreviewSegmentResponses];

export type GetStarredSegmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/segments/starred';
};

export type GetStarredSegmentsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetStarredSegmentsResponses = {
    /**
     * List of starred segments
     */
    200: Array<Segment>;
};

export type GetStarredSegmentsResponse = GetStarredSegmentsResponses[keyof GetStarredSegmentsResponses];

export type GetStarredSegmentEffortsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/segments/starred/efforts';
};

export type GetStarredSegmentEffortsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetStarredSegmentEffortsResponses = {
    /**
     * List of starred segments with effort stats
     */
    200: Array<StarredSegmentEffort>;
};

export type GetStarredSegmentEffortsResponse = GetStarredSegmentEffortsResponses[keyof GetStarredSegmentEffortsResponses];

export type GetSegmentData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}';
};

export type GetSegmentErrors = {
    /**
     * Segment not found
     */
    404: unknown;
};

export type GetSegmentResponses = {
    /**
     * Segment details
     */
    200: Segment;
};

export type GetSegmentResponse = GetSegmentResponses[keyof GetSegmentResponses];

export type GetSegmentAchievementsData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/achievements';
};

export type GetSegmentAchievementsErrors = {
    /**
     * Segment not found
     */
    404: unknown;
};

export type GetSegmentAchievementsResponses = {
    /**
     * Segment achievement holders
     */
    200: SegmentAchievements;
};

export type GetSegmentAchievementsResponse = GetSegmentAchievementsResponses[keyof GetSegmentAchievementsResponses];

export type GetMySegmentEffortsData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/efforts/me';
};

export type GetMySegmentEffortsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Segment not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetMySegmentEffortsResponses = {
    /**
     * User's efforts on segment
     */
    200: Array<SegmentEffort>;
};

export type GetMySegmentEffortsResponse = GetMySegmentEffortsResponses[keyof GetMySegmentEffortsResponses];

export type GetSegmentLeaderboardData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/leaderboard';
};

export type GetSegmentLeaderboardErrors = {
    /**
     * Segment not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetSegmentLeaderboardResponses = {
    /**
     * Segment leaderboard
     */
    200: Array<SegmentEffort>;
};

export type GetSegmentLeaderboardResponse = GetSegmentLeaderboardResponses[keyof GetSegmentLeaderboardResponses];

export type GetFilteredLeaderboardData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: {
        scope?: LeaderboardScope;
        gender?: GenderFilter;
        age_group?: AgeGroup;
        weight_class?: WeightClass;
        country?: string | null;
        limit?: number;
        offset?: number;
    };
    url: '/segments/{id}/leaderboard/filtered';
};

export type GetFilteredLeaderboardErrors = {
    /**
     * Segment not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetFilteredLeaderboardResponses = {
    /**
     * Filtered leaderboard
     */
    200: LeaderboardResponse;
};

export type GetFilteredLeaderboardResponse = GetFilteredLeaderboardResponses[keyof GetFilteredLeaderboardResponses];

export type GetLeaderboardPositionData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: {
        scope?: LeaderboardScope;
        gender?: GenderFilter;
        age_group?: AgeGroup;
        weight_class?: WeightClass;
        country?: string | null;
        limit?: number;
        offset?: number;
    };
    url: '/segments/{id}/leaderboard/position';
};

export type GetLeaderboardPositionErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Segment not found or user has no efforts
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetLeaderboardPositionResponses = {
    /**
     * User's leaderboard position with surrounding entries
     */
    200: LeaderboardPosition;
};

export type GetLeaderboardPositionResponse = GetLeaderboardPositionResponses[keyof GetLeaderboardPositionResponses];

export type ReprocessSegmentData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/reprocess';
};

export type ReprocessSegmentErrors = {
    /**
     * Segment not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ReprocessSegmentResponses = {
    /**
     * Reprocessing results
     */
    200: ReprocessResult;
};

export type ReprocessSegmentResponse = ReprocessSegmentResponses[keyof ReprocessSegmentResponses];

export type UnstarSegmentData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/star';
};

export type UnstarSegmentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UnstarSegmentResponses = {
    /**
     * Segment unstarred successfully
     */
    200: StarResponse;
};

export type UnstarSegmentResponse = UnstarSegmentResponses[keyof UnstarSegmentResponses];

export type StarSegmentData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/star';
};

export type StarSegmentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Segment not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type StarSegmentResponses = {
    /**
     * Segment starred successfully
     */
    200: StarResponse;
};

export type StarSegmentResponse = StarSegmentResponses[keyof StarSegmentResponses];

export type IsSegmentStarredData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/starred';
};

export type IsSegmentStarredErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type IsSegmentStarredResponses = {
    /**
     * Starred status
     */
    200: StarResponse;
};

export type IsSegmentStarredResponse = IsSegmentStarredResponses[keyof IsSegmentStarredResponses];

export type GetSegmentTeamsData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/teams';
};

export type GetSegmentTeamsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Segment not found
     */
    404: unknown;
};

export type GetSegmentTeamsResponses = {
    /**
     * Teams the segment is shared with
     */
    200: Array<TeamSummary>;
};

export type GetSegmentTeamsResponse = GetSegmentTeamsResponses[keyof GetSegmentTeamsResponses];

export type ShareSegmentWithTeamsData = {
    body: ShareWithTeamsRequest;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/teams';
};

export type ShareSegmentWithTeamsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - not the creator
     */
    403: unknown;
    /**
     * Segment not found
     */
    404: unknown;
};

export type ShareSegmentWithTeamsResponses = {
    /**
     * Segment shared with teams
     */
    200: unknown;
};

export type GetSegmentTrackData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        id: string;
    };
    query?: never;
    url: '/segments/{id}/track';
};

export type GetSegmentTrackErrors = {
    /**
     * Unauthorized - private segment requires authentication
     */
    401: unknown;
    /**
     * Segment not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetSegmentTrackResponses = {
    /**
     * Segment track data with points and bounds
     */
    200: SegmentTrackData;
};

export type GetSegmentTrackResponse = GetSegmentTrackResponses[keyof GetSegmentTrackResponses];

export type UnshareSegmentFromTeamData = {
    body?: never;
    path: {
        /**
         * Segment ID
         */
        segment_id: string;
        /**
         * Team ID
         */
        team_id: string;
    };
    query?: never;
    url: '/segments/{segment_id}/teams/{team_id}';
};

export type UnshareSegmentFromTeamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - not the creator
     */
    403: unknown;
    /**
     * Segment or sharing not found
     */
    404: unknown;
};

export type UnshareSegmentFromTeamResponses = {
    /**
     * Segment unshared from team
     */
    204: void;
};

export type UnshareSegmentFromTeamResponse = UnshareSegmentFromTeamResponses[keyof UnshareSegmentFromTeamResponses];

export type GetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetStatsResponses = {
    /**
     * Platform statistics
     */
    200: Stats;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type ListMyTeamsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/teams';
};

export type ListMyTeamsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListMyTeamsResponses = {
    /**
     * List of teams user is a member of
     */
    200: Array<TeamWithMembership>;
};

export type ListMyTeamsResponse = ListMyTeamsResponses[keyof ListMyTeamsResponses];

export type CreateTeamData = {
    body: CreateTeamRequest;
    path?: never;
    query?: never;
    url: '/teams';
};

export type CreateTeamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CreateTeamResponses = {
    /**
     * Team created
     */
    201: Team;
};

export type CreateTeamResponse = CreateTeamResponses[keyof CreateTeamResponses];

export type DiscoverTeamsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of teams to return
         */
        limit?: number;
        /**
         * Number of teams to skip
         */
        offset?: number;
    };
    url: '/teams/discover';
};

export type DiscoverTeamsResponses = {
    /**
     * List of discoverable teams
     */
    200: Array<TeamSummary>;
};

export type DiscoverTeamsResponse = DiscoverTeamsResponses[keyof DiscoverTeamsResponses];

export type DeleteTeamData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}';
};

export type DeleteTeamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - insufficient permissions
     */
    403: unknown;
    /**
     * Team not found
     */
    404: unknown;
};

export type DeleteTeamResponses = {
    /**
     * Team deleted
     */
    204: void;
};

export type DeleteTeamResponse = DeleteTeamResponses[keyof DeleteTeamResponses];

export type GetTeamData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}';
};

export type GetTeamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Team not found
     */
    404: unknown;
};

export type GetTeamResponses = {
    /**
     * Team details with membership context
     */
    200: TeamWithMembership;
};

export type GetTeamResponse = GetTeamResponses[keyof GetTeamResponses];

export type UpdateTeamData = {
    body: UpdateTeamRequest;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}';
};

export type UpdateTeamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - insufficient permissions
     */
    403: unknown;
    /**
     * Team not found
     */
    404: unknown;
};

export type UpdateTeamResponses = {
    /**
     * Team updated
     */
    200: Team;
};

export type UpdateTeamResponse = UpdateTeamResponses[keyof UpdateTeamResponses];

export type GetTeamActivitiesData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: {
        /**
         * Maximum number of results
         */
        limit?: number;
        /**
         * Number of results to skip
         */
        offset?: number;
    };
    url: '/teams/{id}/activities';
};

export type GetTeamActivitiesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Team not found or not a member
     */
    404: unknown;
};

export type GetTeamActivitiesResponses = {
    /**
     * Activities shared with the team
     */
    200: Array<FeedActivity>;
};

export type GetTeamActivitiesResponse = GetTeamActivitiesResponses[keyof GetTeamActivitiesResponses];

export type GetTeamInvitationsData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}/invitations';
};

export type GetTeamInvitationsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - insufficient permissions
     */
    403: unknown;
    /**
     * Team not found
     */
    404: unknown;
};

export type GetTeamInvitationsResponses = {
    /**
     * List of pending invitations
     */
    200: Array<TeamInvitation>;
};

export type GetTeamInvitationsResponse = GetTeamInvitationsResponses[keyof GetTeamInvitationsResponses];

export type InviteToTeamData = {
    body: InviteToTeamRequest;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}/invitations';
};

export type InviteToTeamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - insufficient permissions
     */
    403: unknown;
    /**
     * Team not found
     */
    404: unknown;
};

export type InviteToTeamResponses = {
    /**
     * Invitation created
     */
    201: TeamInvitation;
};

export type InviteToTeamResponse = InviteToTeamResponses[keyof InviteToTeamResponses];

export type JoinTeamData = {
    body: JoinTeamRequest;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}/join';
};

export type JoinTeamErrors = {
    /**
     * Already a member or invitation-only team
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Team not found
     */
    404: unknown;
};

export type JoinTeamResponses = {
    /**
     * Joined team directly (open policy)
     */
    201: unknown;
    /**
     * Join request submitted (request policy)
     */
    202: unknown;
};

export type GetJoinRequestsData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}/join-requests';
};

export type GetJoinRequestsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Team not found
     */
    404: unknown;
};

export type GetJoinRequestsResponses = {
    /**
     * List of pending join requests
     */
    200: Array<TeamJoinRequestWithUser>;
};

export type GetJoinRequestsResponse = GetJoinRequestsResponses[keyof GetJoinRequestsResponses];

export type LeaveTeamData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}/leave';
};

export type LeaveTeamErrors = {
    /**
     * Owner cannot leave team
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Team not found or not a member
     */
    404: unknown;
};

export type LeaveTeamResponses = {
    /**
     * Left team
     */
    204: void;
};

export type LeaveTeamResponse = LeaveTeamResponses[keyof LeaveTeamResponses];

export type ListTeamMembersData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: never;
    url: '/teams/{id}/members';
};

export type ListTeamMembersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Team not found
     */
    404: unknown;
};

export type ListTeamMembersResponses = {
    /**
     * List of team members
     */
    200: Array<TeamMember>;
};

export type ListTeamMembersResponse = ListTeamMembersResponses[keyof ListTeamMembersResponses];

export type GetTeamSegmentsData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        id: string;
    };
    query?: {
        /**
         * Maximum number of results
         */
        limit?: number;
        /**
         * Number of results to skip
         */
        offset?: number;
    };
    url: '/teams/{id}/segments';
};

export type GetTeamSegmentsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Team not found or not a member
     */
    404: unknown;
};

export type GetTeamSegmentsResponses = {
    /**
     * Segments shared with the team
     */
    200: Array<Segment>;
};

export type GetTeamSegmentsResponse = GetTeamSegmentsResponses[keyof GetTeamSegmentsResponses];

export type RevokeInvitationData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        team_id: string;
        /**
         * Invitation ID
         */
        invitation_id: string;
    };
    query?: never;
    url: '/teams/{team_id}/invitations/{invitation_id}';
};

export type RevokeInvitationErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - insufficient permissions
     */
    403: unknown;
    /**
     * Invitation not found
     */
    404: unknown;
};

export type RevokeInvitationResponses = {
    /**
     * Invitation revoked
     */
    204: void;
};

export type RevokeInvitationResponse = RevokeInvitationResponses[keyof RevokeInvitationResponses];

export type ReviewJoinRequestData = {
    body: ReviewJoinRequestRequest;
    path: {
        /**
         * Team ID
         */
        team_id: string;
        /**
         * Join request ID
         */
        request_id: string;
    };
    query?: never;
    url: '/teams/{team_id}/join-requests/{request_id}';
};

export type ReviewJoinRequestErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Team or request not found
     */
    404: unknown;
};

export type ReviewJoinRequestResponses = {
    /**
     * Request reviewed
     */
    204: void;
};

export type ReviewJoinRequestResponse = ReviewJoinRequestResponses[keyof ReviewJoinRequestResponses];

export type RemoveTeamMemberData = {
    body?: never;
    path: {
        /**
         * Team ID
         */
        team_id: string;
        /**
         * User ID
         */
        user_id: string;
    };
    query?: never;
    url: '/teams/{team_id}/members/{user_id}';
};

export type RemoveTeamMemberErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Team or member not found
     */
    404: unknown;
};

export type RemoveTeamMemberResponses = {
    /**
     * Member removed
     */
    204: void;
};

export type RemoveTeamMemberResponse = RemoveTeamMemberResponses[keyof RemoveTeamMemberResponses];

export type ChangeMemberRoleData = {
    body: ChangeMemberRoleRequest;
    path: {
        /**
         * Team ID
         */
        team_id: string;
        /**
         * User ID
         */
        user_id: string;
    };
    query?: never;
    url: '/teams/{team_id}/members/{user_id}/role';
};

export type ChangeMemberRoleErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Team or member not found
     */
    404: unknown;
};

export type ChangeMemberRoleResponses = {
    /**
     * Role changed
     */
    200: TeamMembership;
};

export type ChangeMemberRoleResponse = ChangeMemberRoleResponses[keyof ChangeMemberRoleResponses];

export type AllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type AllUsersResponses = {
    /**
     * List of all users
     */
    200: Array<User>;
};

export type AllUsersResponse = AllUsersResponses[keyof AllUsersResponses];

export type GetMyDemographicsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/demographics';
};

export type GetMyDemographicsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type GetMyDemographicsResponses = {
    /**
     * User demographics
     */
    200: UserWithDemographics;
};

export type GetMyDemographicsResponse = GetMyDemographicsResponses[keyof GetMyDemographicsResponses];

export type UpdateMyDemographicsData = {
    body: UpdateDemographicsRequest;
    path?: never;
    query?: never;
    url: '/users/me/demographics';
};

export type UpdateMyDemographicsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type UpdateMyDemographicsResponses = {
    /**
     * Demographics updated successfully
     */
    200: UserWithDemographics;
};

export type UpdateMyDemographicsResponse = UpdateMyDemographicsResponses[keyof UpdateMyDemographicsResponses];

export type NewUserData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User's name
         */
        name: string;
        /**
         * User's email address
         */
        email: string;
    };
    url: '/users/new';
};

export type NewUserErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type NewUserResponses = {
    /**
     * User created successfully
     */
    200: User;
};

export type NewUserResponse = NewUserResponses[keyof NewUserResponses];

export type GetUserAchievementsData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: {
        include_lost?: boolean;
    };
    url: '/users/{id}/achievements';
};

export type GetUserAchievementsErrors = {
    /**
     * User not found
     */
    404: unknown;
};

export type GetUserAchievementsResponses = {
    /**
     * User achievements
     */
    200: Array<AchievementWithSegment>;
};

export type GetUserAchievementsResponse = GetUserAchievementsResponses[keyof GetUserAchievementsResponses];

export type GetUserActivitiesData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/activities';
};

export type GetUserActivitiesResponses = {
    /**
     * List of user's activities
     */
    200: Array<Activity>;
};

export type GetUserActivitiesResponse = GetUserActivitiesResponses[keyof GetUserActivitiesResponses];

export type UnfollowUserData = {
    body?: never;
    path: {
        /**
         * User ID to unfollow
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/follow';
};

export type UnfollowUserErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Was not following this user
     */
    404: unknown;
};

export type UnfollowUserResponses = {
    /**
     * Successfully unfollowed user
     */
    204: void;
};

export type UnfollowUserResponse = UnfollowUserResponses[keyof UnfollowUserResponses];

export type FollowUserData = {
    body?: never;
    path: {
        /**
         * User ID to follow
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/follow';
};

export type FollowUserErrors = {
    /**
     * Cannot follow yourself
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type FollowUserResponses = {
    /**
     * Already following (idempotent)
     */
    200: unknown;
    /**
     * Successfully followed user
     */
    201: unknown;
};

export type GetFollowStatusData = {
    body?: never;
    path: {
        /**
         * User ID to check follow status for
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/follow/status';
};

export type GetFollowStatusErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetFollowStatusResponses = {
    /**
     * Follow status retrieved
     */
    200: FollowStatusResponse;
};

export type GetFollowStatusResponse = GetFollowStatusResponses[keyof GetFollowStatusResponses];

export type GetFollowersData = {
    body?: never;
    path: {
        /**
         * User ID to get followers for
         */
        id: string;
    };
    query?: {
        /**
         * Maximum number of results
         */
        limit?: number;
        /**
         * Offset for pagination
         */
        offset?: number;
    };
    url: '/users/{id}/followers';
};

export type GetFollowersResponses = {
    /**
     * Followers retrieved
     */
    200: FollowListResponse;
};

export type GetFollowersResponse = GetFollowersResponses[keyof GetFollowersResponses];

export type GetFollowingData = {
    body?: never;
    path: {
        /**
         * User ID to get following list for
         */
        id: string;
    };
    query?: {
        /**
         * Maximum number of results
         */
        limit?: number;
        /**
         * Offset for pagination
         */
        offset?: number;
    };
    url: '/users/{id}/following';
};

export type GetFollowingResponses = {
    /**
     * Following list retrieved
     */
    200: FollowListResponse;
};

export type GetFollowingResponse = GetFollowingResponses[keyof GetFollowingResponses];

export type GetUserProfileData = {
    body?: never;
    path: {
        /**
         * User ID to get profile for
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/profile';
};

export type GetUserProfileErrors = {
    /**
     * User not found
     */
    404: unknown;
};

export type GetUserProfileResponses = {
    /**
     * User profile retrieved
     */
    200: UserProfile;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];
