// This file is auto-generated by @hey-api/openapi-ts

/**
 * An achievement/crown earned by a user
 */
export type Achievement = {
    achievement_type: AchievementType;
    created_at: string;
    earned_at: string;
    effort_count?: (number) | null;
    effort_id?: (string) | null;
    id: string;
    lost_at?: (string) | null;
    segment_id: string;
    user_id: string;
};

/**
 * Holder of an achievement with their details
 */
export type AchievementHolder = {
    achievement_type: AchievementType;
    earned_at: string;
    effort_count?: (number) | null;
    elapsed_time_seconds?: (number) | null;
    user_id: string;
    user_name: string;
};

/**
 * Type of achievement/crown
 */
export type AchievementType = 'kom' | 'qom' | 'local_legend' | 'course_record';

/**
 * Achievement with segment details for display
 */
export type AchievementWithSegment = {
    achievement_type: AchievementType;
    earned_at: string;
    effort_count?: (number) | null;
    effort_id?: (string) | null;
    id: string;
    lost_at?: (string) | null;
    segment_activity_type_id: string;
    segment_distance_meters: number;
    segment_id: string;
    segment_name: string;
    user_id: string;
};

export type Activity = {
    activity_type_id: string;
    id: string;
    name: string;
    object_store_path: string;
    segment_types?: Array<(string)> | null;
    submitted_at: string;
    type_boundaries?: Array<(string)> | null;
    user_id: string;
    visibility: string;
};

/**
 * Segment effort with segment details, for displaying on activity detail page.
 */
export type ActivitySegmentEffort = {
    activity_type_id: string;
    effort_id: string;
    elapsed_time_seconds: number;
    end_fraction?: (number) | null;
    is_personal_record: boolean;
    rank: number;
    segment_distance: number;
    segment_id: string;
    segment_name: string;
    start_fraction?: (number) | null;
    started_at: string;
};

/**
 * Row from the activity_types table
 */
export type ActivityTypeRow = {
    created_at: string;
    created_by?: (string) | null;
    id: string;
    is_builtin: boolean;
    name: string;
};

export type AddCommentRequest = {
    content: string;
    parent_id?: (string) | null;
};

/**
 * Age group for demographic filtering (5-year brackets for younger, 10-year for older)
 */
export type AgeGroup = 'all' | '18-24' | '25-29' | '30-34' | '35-39' | '40-49' | '50-59' | '60+';

export type AuthResponse = {
    token: string;
    user: UserResponse;
};

/**
 * Request to change a member's role
 */
export type ChangeMemberRoleRequest = {
    role: TeamRole;
};

export type ClimbCategoryFilter = 'hc' | 'cat1' | 'cat2' | 'cat3' | 'cat4' | 'flat';

/**
 * A comment on an activity
 */
export type Comment = {
    activity_id: string;
    content: string;
    created_at: string;
    deleted_at?: (string) | null;
    id: string;
    parent_id?: (string) | null;
    updated_at?: (string) | null;
    user_id: string;
};

/**
 * Comment with user info for display
 */
export type CommentWithUser = {
    activity_id: string;
    content: string;
    created_at: string;
    id: string;
    parent_id?: (string) | null;
    updated_at?: (string) | null;
    user_id: string;
    user_name: string;
};

/**
 * Country with user count for the countries dropdown
 */
export type CountryStats = {
    country: string;
    user_count: number;
};

/**
 * Request to create a custom activity type
 */
export type CreateActivityTypeRequest = {
    name: string;
};

export type CreateSegmentRequest = {
    /**
     * Optional if source_activity_id is provided (inherits from the activity).
     * Required if source_activity_id is not provided.
     */
    activity_type_id?: (string) | null;
    description?: (string) | null;
    name: string;
    points: Array<SegmentPoint>;
    /**
     * Optional: the activity this segment was created from.
     * If provided, the segment inherits its activity_type_id and guarantees that activity gets the first effort.
     */
    source_activity_id?: (string) | null;
    /**
     * Team IDs to share the segment with (for teams_only visibility)
     */
    team_ids?: Array<(string)> | null;
    visibility?: string;
};

/**
 * Request to create a team
 */
export type CreateTeamRequest = {
    avatar_url?: (string) | null;
    description?: (string) | null;
    join_policy?: TeamJoinPolicy;
    name: string;
    visibility?: TeamVisibility;
};

/**
 * Entry in global crown count leaderboard
 */
export type CrownCountEntry = {
    kom_count: number;
    local_legend_count: number;
    qom_count: number;
    rank: number;
    total_crowns: number;
    user_id: string;
    user_name: string;
};

export type DiscoverTeamsQuery = {
    limit?: number;
    offset?: number;
};

/**
 * Entry in global distance leaderboard
 */
export type DistanceLeaderEntry = {
    activity_count: number;
    rank: number;
    total_distance_meters: number;
    user_id: string;
    user_name: string;
};

/**
 * Activity with user and stats for the feed
 */
export type FeedActivity = {
    activity_type_id: string;
    comment_count: number;
    distance?: (number) | null;
    duration?: (number) | null;
    elevation_gain?: (number) | null;
    id: string;
    kudos_count: number;
    name: string;
    submitted_at: string;
    user_id: string;
    user_name: string;
    visibility: string;
};

export type FeedQuery = {
    limit?: number;
    offset?: number;
};

/**
 * A follow relationship between two users
 */
export type Follow = {
    created_at: string;
    follower_id: string;
    following_id: string;
};

export type FollowListQuery = {
    limit?: number;
    offset?: number;
};

export type FollowListResponse = {
    total_count: number;
    users: Array<UserSummary>;
};

export type FollowStatusResponse = {
    is_following: boolean;
};

/**
 * User gender for demographic filtering
 */
export type Gender = 'male' | 'female' | 'other' | 'prefer_not_to_say';

/**
 * Gender filter for leaderboards (includes "all" option)
 */
export type GenderFilter = 'all' | 'male' | 'female';

/**
 * Get achievements for a specific user.
 */
export type GetAchievementsQuery = {
    include_lost?: boolean;
};

export type GlobalLeaderboardQuery = {
    limit?: number;
    offset?: number;
};

/**
 * Request to invite a user to a team
 */
export type InviteToTeamRequest = {
    email: string;
    role?: TeamRole;
};

/**
 * Request to join a team
 */
export type JoinTeamRequest = {
    message?: (string) | null;
};

/**
 * User who gave kudos
 */
export type KudosGiver = {
    created_at: string;
    user_id: string;
    user_name: string;
};

export type KudosResponse = {
    given: boolean;
    kudos_count: number;
};

export type KudosStatusResponse = {
    has_given: boolean;
};

/**
 * A single entry in the leaderboard with user info and ranking
 */
export type LeaderboardEntry = {
    average_speed_mps?: (number) | null;
    effort_id: string;
    elapsed_time_seconds: number;
    gap_seconds?: (number) | null;
    is_personal_record: boolean;
    moving_time_seconds?: (number) | null;
    rank: number;
    started_at: string;
    user_id: string;
    user_name: string;
};

/**
 * Query parameters for filtered leaderboard requests
 */
export type LeaderboardFilters = {
    age_group?: AgeGroup;
    country?: (string) | null;
    gender?: GenderFilter;
    limit?: number;
    offset?: number;
    scope?: LeaderboardScope;
    weight_class?: WeightClass;
};

/**
 * Echoed filters in leaderboard response
 */
export type LeaderboardFiltersResponse = {
    age_group: AgeGroup;
    country?: (string) | null;
    gender: GenderFilter;
    limit: number;
    offset: number;
    scope: LeaderboardScope;
    weight_class: WeightClass;
};

/**
 * User's position in the leaderboard with surrounding entries
 */
export type LeaderboardPosition = {
    entries_above: Array<LeaderboardEntry>;
    entries_below: Array<LeaderboardEntry>;
    total_count: number;
    user_entry: LeaderboardEntry;
    user_rank: number;
};

/**
 * Response for paginated leaderboard
 */
export type LeaderboardResponse = {
    entries: Array<LeaderboardEntry>;
    filters: LeaderboardFiltersResponse;
    total_count: number;
};

/**
 * Time scope for leaderboard filtering
 */
export type LeaderboardScope = 'all_time' | 'year' | 'month' | 'week';

export type ListSegmentsQuery = {
    activity_type_id?: (string) | null;
    climb_category?: (null | ClimbCategoryFilter);
    limit?: number;
    /**
     * Maximum distance in meters
     */
    max_distance_meters?: (number) | null;
    /**
     * Minimum distance in meters
     */
    min_distance_meters?: (number) | null;
    /**
     * Case-insensitive name search
     */
    search?: (string) | null;
    /**
     * Sort field
     */
    sort_by?: SegmentSortBy;
    /**
     * Sort order
     */
    sort_order?: SortOrder;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type NearbySegmentsQuery = {
    lat: number;
    limit?: (number) | null;
    lon: number;
    radius_meters?: (number) | null;
};

/**
 * A notification for a user
 */
export type Notification = {
    actor_id?: (string) | null;
    created_at: string;
    id: string;
    message?: (string) | null;
    notification_type: string;
    read_at?: (string) | null;
    target_id?: (string) | null;
    target_type?: (string) | null;
    user_id: string;
};

export type NotificationsQuery = {
    limit?: number;
    offset?: number;
};

/**
 * Response for notifications list with unread count
 */
export type NotificationsResponse = {
    notifications: Array<NotificationWithActor>;
    total_count: number;
    unread_count: number;
};

/**
 * Type of notification
 */
export type NotificationType = 'follow' | 'kudos' | 'comment' | 'crown_achieved' | 'crown_lost' | 'personal_record';

/**
 * Notification with actor details for display
 */
export type NotificationWithActor = {
    actor_id?: (string) | null;
    actor_name?: (string) | null;
    created_at: string;
    id: string;
    message?: (string) | null;
    notification_type: string;
    read_at?: (string) | null;
    target_id?: (string) | null;
    target_type?: (string) | null;
    user_id: string;
};

export type PreviewSegmentRequest = {
    points: Array<SegmentPoint>;
};

export type PreviewSegmentResponse = {
    average_grade?: (number) | null;
    climb_category?: (number) | null;
    distance_meters: number;
    elevation_gain_meters?: (number) | null;
    elevation_loss_meters?: (number) | null;
    max_grade?: (number) | null;
    point_count: number;
    validation: SegmentValidation;
};

export type RegisterRequest = {
    email: string;
    name: string;
    password: string;
};

export type ReprocessResult = {
    activities_checked: number;
    efforts_created: number;
    segment_id: string;
};

/**
 * Resolve an activity type by name or alias.
 */
export type ResolveTypeQuery = {
    name: string;
};

export type ResolveTypeResponse = {
    result: string;
    type_id?: (string) | null;
    type_ids?: Array<(string)> | null;
};

export type ReviewJoinRequestRequest = {
    approved: boolean;
};

export type Segment = {
    activity_type_id: string;
    average_grade?: (number) | null;
    climb_category?: (number) | null;
    created_at: string;
    creator_id: string;
    description?: (string) | null;
    distance_meters: number;
    elevation_gain_meters?: (number) | null;
    elevation_loss_meters?: (number) | null;
    id: string;
    max_grade?: (number) | null;
    name: string;
    visibility: string;
};

/**
 * Current achievement holders for a segment
 */
export type SegmentAchievements = {
    kom?: (null | AchievementHolder);
    local_legend?: (null | AchievementHolder);
    qom?: (null | AchievementHolder);
    segment_id: string;
};

export type SegmentEffort = {
    activity_id: string;
    average_speed_mps?: (number) | null;
    created_at: string;
    elapsed_time_seconds: number;
    end_fraction?: (number) | null;
    id: string;
    is_personal_record: boolean;
    max_speed_mps?: (number) | null;
    moving_time_seconds?: (number) | null;
    segment_id: string;
    start_fraction?: (number) | null;
    started_at: string;
    user_id: string;
};

export type SegmentPoint = {
    ele?: (number) | null;
    lat: number;
    lon: number;
};

export type SegmentSortBy = 'created_at' | 'name' | 'distance' | 'elevation_gain';

export type SegmentTrackData = {
    bounds: TrackBounds;
    points: Array<SegmentTrackPoint>;
};

export type SegmentTrackPoint = {
    ele?: (number) | null;
    lat: number;
    lon: number;
};

export type SegmentValidation = {
    errors: Array<(string)>;
    is_valid: boolean;
};

export type SegmentWithStats = Segment & {
    athlete_count: number;
    creator_name: string;
    effort_count: number;
};

/**
 * Request to share activity/segment with teams
 */
export type ShareWithTeamsRequest = {
    team_ids: Array<(string)>;
};

export type SortOrder = 'asc' | 'desc';

/**
 * Starred segment with the user's effort stats, for the starred segments dashboard.
 */
export type StarredSegmentEffort = {
    activity_type_id: string;
    best_effort_date?: (string) | null;
    best_effort_rank?: (number) | null;
    best_time_seconds?: (number) | null;
    distance_meters: number;
    elevation_gain_meters?: (number) | null;
    leader_time_seconds?: (number) | null;
    segment_id: string;
    segment_name: string;
    user_effort_count: number;
};

export type StarResponse = {
    starred: boolean;
};

/**
 * Platform statistics for the homepage
 */
export type Stats = {
    active_users: number;
    activities_uploaded: number;
    segments_created: number;
};

/**
 * A team for sharing activities and segments
 */
export type Team = {
    activity_count: number;
    avatar_url?: (string) | null;
    created_at: string;
    description?: (string) | null;
    id: string;
    join_policy: TeamJoinPolicy;
    member_count: number;
    name: string;
    owner_id: string;
    segment_count: number;
    updated_at?: (string) | null;
    visibility: TeamVisibility;
};

export type TeamContentQuery = {
    limit?: number;
    offset?: number;
};

/**
 * An invitation to join a team
 */
export type TeamInvitation = {
    accepted_at?: (string) | null;
    created_at: string;
    email: string;
    expires_at: string;
    id: string;
    invited_by: string;
    role: TeamRole;
    team_id: string;
    token: string;
};

/**
 * Invitation with additional context
 */
export type TeamInvitationWithDetails = {
    created_at: string;
    email: string;
    expires_at: string;
    id: string;
    invited_by: string;
    invited_by_name: string;
    role: TeamRole;
    team_id: string;
    team_name: string;
};

/**
 * Team join policy
 */
export type TeamJoinPolicy = 'open' | 'request' | 'invitation';

/**
 * Request to join a team
 */
export type TeamJoinRequest = {
    created_at: string;
    id: string;
    message?: (string) | null;
    reviewed_at?: (string) | null;
    reviewed_by?: (string) | null;
    status: string;
    team_id: string;
    user_id: string;
};

/**
 * Join request with user details for admin review
 */
export type TeamJoinRequestWithUser = {
    created_at: string;
    id: string;
    message?: (string) | null;
    status: string;
    team_id: string;
    user_id: string;
    user_name: string;
};

/**
 * Team member with user details
 */
export type TeamMember = {
    invited_by?: (string) | null;
    invited_by_name?: (string) | null;
    joined_at: string;
    role: TeamRole;
    user_id: string;
    user_name: string;
};

/**
 * A membership in a team
 */
export type TeamMembership = {
    invited_by?: (string) | null;
    joined_at: string;
    role: TeamRole;
    team_id: string;
    user_id: string;
};

/**
 * Team role enum
 */
export type TeamRole = 'owner' | 'admin' | 'member';

/**
 * Team summary for listings
 */
export type TeamSummary = {
    activity_count: number;
    avatar_url?: (string) | null;
    description?: (string) | null;
    id: string;
    member_count: number;
    name: string;
    segment_count: number;
};

/**
 * Team visibility (whether team is discoverable)
 */
export type TeamVisibility = 'public' | 'private';

/**
 * Team with additional context for the current user
 */
export type TeamWithMembership = Team & {
    is_member: boolean;
    owner_name: string;
    user_role?: (null | TeamRole);
};

export type TrackBounds = {
    max_lat: number;
    max_lon: number;
    min_lat: number;
    min_lon: number;
};

export type TrackData = {
    bounds: TrackBounds;
    points: Array<TrackPoint>;
};

export type TrackPoint = {
    ele?: (number) | null;
    lat: number;
    lon: number;
    time?: (string) | null;
};

export type UpdateActivityRequest = {
    activity_type_id?: (string) | null;
    name?: (string) | null;
    visibility?: (string) | null;
};

/**
 * Request to update user demographics
 */
export type UpdateDemographicsRequest = {
    birth_year?: (number) | null;
    country?: (string) | null;
    gender?: (null | Gender);
    region?: (string) | null;
    weight_kg?: (number) | null;
};

/**
 * Request to update a team
 */
export type UpdateTeamRequest = {
    avatar_url?: (string) | null;
    description?: (string) | null;
    join_policy?: (null | TeamJoinPolicy);
    name?: (string) | null;
    visibility?: (null | TeamVisibility);
};

export type UploadQuery = {
    activity_type_id: string;
    name: string;
    /**
     * Multi-sport: JSON array of activity type UUIDs for each segment
     */
    segment_types?: Array<(string)> | null;
    /**
     * Comma-separated list of team IDs to share with (for teams_only visibility)
     */
    team_ids?: (string) | null;
    /**
     * Multi-sport: JSON array of ISO-8601 timestamps marking segment boundaries
     */
    type_boundaries?: Array<(string)> | null;
    visibility?: (string) | null;
};

export type User = {
    created_at: string;
    email: string;
    id: string;
    name: string;
};

/**
 * User profile with follow counts for display
 */
export type UserProfile = {
    birth_year?: (number) | null;
    country?: (string) | null;
    created_at: string;
    email: string;
    follower_count: number;
    following_count: number;
    gender?: (null | Gender);
    id: string;
    name: string;
    region?: (string) | null;
    weight_kg?: (number) | null;
};

export type UserResponse = {
    email: string;
    id: string;
    name: string;
};

/**
 * Summary of a user for follower/following lists
 */
export type UserSummary = {
    followed_at: string;
    follower_count: number;
    following_count: number;
    id: string;
    name: string;
};

/**
 * User profile with demographics
 */
export type UserWithDemographics = {
    birth_year?: (number) | null;
    country?: (string) | null;
    created_at: string;
    email: string;
    gender?: (null | Gender);
    id: string;
    name: string;
    region?: (string) | null;
    weight_kg?: (number) | null;
};

export type Visibility = 'public' | 'private';

/**
 * Weight class for leaderboard filtering
 */
export type WeightClass = 'all' | 'featherweight' | 'lightweight' | 'welterweight' | 'middleweight' | 'cruiserweight' | 'heavyweight';